services:
  - type: web
    name: parts-catalogue
    env: static
    buildCommand: npm install -g pnpm@8.15.6 && pnpm install --no-frozen-lockfile && pnpm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PNPM_VERSION
        value: "8.15.6"
      - key: VITE_CF_PUBLIC_BASE
        sync: false
      - key: VITE_R2_PUBLIC_BASE
        sync: false
      - key: VITE_R2_ENDPOINT
        sync: false
      - key: VITE_R2_BUCKET
        sync: false
      - key: VITE_R2_ACCESS_KEY
        sync: false
      - key: VITE_R2_SECRET_KEY
        sync: false
      - key: VITE_EMAILJS_SERVICE_ID
        sync: false
      - key: VITE_EMAILJS_PUBLIC_KEY
        sync: false
      - key: VITE_EMAILJS_PRIVATE_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
